SUBROUTINE ALLOCATEVAR2()

USE VAR

IMPLICIT NONE  

!Neighbour list variables
  
  !     SETS UP A LIST OF THE TWENTY SIX NEIGHBOURING
  !     CELLS OF EACH OF THE SMALL CELLS IN THE CENTRAL BOX.
  
  NCELLX_ATOM = INT(BOXX/RLIST_ATOM)
  NCELLY_ATOM = INT(BOXY/RLIST_ATOM)
  NCELLZ_ATOM = INT(BOXZ/RLIST_ATOM)
  NUMCELL_ATOM = NCELLX_ATOM * NCELLY_ATOM * NCELLZ_ATOM 


  MAPSIZE_ATOM = 13 * NUMCELL_ATOM 
  MAXNUMCELL_ATOM = NUMCELL_ATOM * 10
  MAXMAPSIZE_ATOM = MAPSIZE_ATOM * 10
  MAXNAB_ATOM = 1000 * NATOMS

  ALLOCATE (MAP_ATOM(MAXMAPSIZE_ATOM) )
  ALLOCATE (CELL_ATOM(NITEMS) )
  ALLOCATE (HEAD_ATOM(MAXNUMCELL_ATOM) )
  ALLOCATE (LCLIST_ATOM(NITEMS) )
  ALLOCATE (NCELL_ATOM(MAXNUMCELL_ATOM) )
  ALLOCATE (INDX_ATOM(MAXNUMCELL_ATOM, NATOMS) )
!  ALLOCATE(POINT_ATOM(NUMATOMS+1))
  ALLOCATE(LIST_ATOM(MAXNAB_ATOM))


  IF(IBRDESCR .eq. 0) THEN

     NCELLX_BEAD = INT(BOXX/RLIST_BEAD)
     NCELLY_BEAD = INT(BOXY/RLIST_BEAD)
     NCELLZ_BEAD = INT(BOXZ/RLIST_BEAD)
     NUMCELL_BEAD = NCELLX_BEAD * NCELLY_BEAD * NCELLZ_BEAD 

     MAPSIZE_BEAD = 13 * NUMCELL_BEAD 
     MAXNUMCELL_BEAD = NUMCELL_BEAD * 10
     MAXMAPSIZE_BEAD = MAPSIZE_BEAD * 10
     MAXNAB_BEAD = 1000 * NATOMS

     ALLOCATE (MAP_BEAD(MAXMAPSIZE_BEAD) )
     ALLOCATE (CELL_BEAD(NITEMS) )
     ALLOCATE (HEAD_BEAD(MAXNUMCELL_BEAD) )
     ALLOCATE (LCLIST_BEAD(NITEMS) )
     ALLOCATE (NCELL_BEAD(MAXNUMCELL_BEAD) )
     ALLOCATE (INDX_BEAD(MAXNUMCELL_BEAD, NATOMS) )
!     ALLOCATE(POINT_BEAD(NCOARSE+1))
     ALLOCATE(LIST_BEAD(MAXNAB_BEAD))

  END IF

END SUBROUTINE ALLOCATEVAR2
