#ifndef DOXY_SKIP
#include "ibi-preprocess.h"
#endif
!> @file
!> @brief Calculate all bonded forces
!!
!> @details Contains, bonds, angles, torsions and out of planes torsions
!! 
!! Called from NEW_FORCE.f90
!!
!> @note Is parallelised using OpenMP

SUBROUTINE BONDED_FORCE()

  USE VAR
  USE OMP_LIB

  IMPLICIT NONE

  INTEGER :: A
  INTEGER :: I, J, K, L, TI, TJ, TK, TL, TIJ, TIJK, TIJKL, TOIJKL
  INTEGER :: NI
  REAL*4, DIMENSION(3) :: RXYZ_I, RXYZ_IJ
  REAL*4, DIMENSION(3) :: FXYZ_I
  REAL*4 :: RIJSQ, RIJ
  REAL*4, DIMENSION(3) :: RXYZ_KJ, RXYZ_JK, RXYZ_KL
  REAL*4 :: RKJ, RJK, RKL
  REAL*4 :: THETA, COSM, SINM, COTANM, COSN, SINN, COTANN, COST, SIGNT, PHI
  REAL*4 :: CT, eps = 1.0D-7, PHI_t
  REAL*4, DIMENSION(3) :: RXYZ_M, RXYZ_N, RXYZ_S
  REAL*4 :: RM, RN
  REAL*4 :: ALPHA, FIJ, VIJ, FIJK, VIJK, FIJKL, VIJKL
  REAL*4, DIMENSION(3) :: FXYZ_IJ, FXYZ_IJK
  REAL*4, DIMENSION(3) :: FXYZ_1, FXYZ_4, FXYZ_12
  REAL*4, DIMENSION(3) :: RXYZ_mN
  REAL*4, DIMENSION(3, NITEMS) :: FXYZ_L

  !$OMP PARALLEL DEFAULT(NONE) &
  !$OMP& SHARED(NITEMS,NATOMS,SXYZ,ITYPE,STEP,R2D)&
  !$OMP& SHARED(NBONDS,JBOND,IBONDT,BINB,NDATB,RBOND,BOND_FORCE,BOND_POT)&
  !$OMP& SHARED(NIJK,JANGLEIJK,KANGLEIJK,IANGT,BINA,ANGLE,BEND_FORCE,BEND_POT)&
  !$OMP& SHARED(NIJKL,JTORIJKL,KTORIJKL,LTORIJKL,ITORT,BINT,NDATT,ANGLE_TOR)&
  !$OMP& SHARED(TOR_FORCE,TOR_POT)&
  !$OMP& SHARED(NOOPIJKL,JOOPIJKL,KOOPIJKL,LOOPIJKL,IOOPT,BINO,NDATO,ANGLE_OOP)&
  !$OMP& SHARED(OOP_FORCE,OOP_POT, EPS)&
#ifdef DETAILED_ATOM
  !$OMP& SHARED(SPEC_ATOM)&
#endif
  !$OMP& SHARED(BOND_TYPE_LABEL, ANGLE_TYPE_LABEL)&
  !$OMP& SHARED(TORSION_TYPE_LABEL, OOP_TYPE_LABEL)&
  !$OMP& PRIVATE(A, I, J, K, L, TI, TJ, TK, TL, TIJ, TIJK, TIJKL, NI, TOIJKL)&
  !$OMP& PRIVATE(RXYZ_I, FXYZ_I)&
  !$OMP& PRIVATE(RXYZ_IJ, RIJSQ, RIJ)&
  !$OMP& PRIVATE(RXYZ_KJ, RKJ)&
  !$OMP& PRIVATE(RXYZ_JK, RJK, RXYZ_KL, RKL)&
  !$OMP& PRIVATE(THETA, COSM, SINM, COTANM, COSN, SINN, COTANN, COST, SIGNT, PHI)&
  !$OMP& PRIVATE(CT, PHI_t)&
  !$OMP& PRIVATE(RXYZ_M, RM, RXYZ_N, RN, RXYZ_S)&
  !$OMP& PRIVATE(ALPHA, FIJ, VIJ, FIJK, VIJK, FIJKL, VIJKL)&
  !$OMP& PRIVATE(FXYZ_IJ, FXYZ_IJK)&
  !$OMP& PRIVATE(FXYZ_1, FXYZ_4, FXYZ_12)&
  !$OMP& PRIVATE(RXYZ_mN)&
  !$OMP& PRIVATE(FXYZ_L)&
  !$OMP& REDUCTION(+:V_BOND, V_ANGLE, V_TORSION, V_OOP)&
  !$OMP& REDUCTION(+:FXYZ)

  FXYZ_L = 0.0

  !$OMP DO SCHEDULE(STATIC,1)
  DO I=1,NITEMS
     RXYZ_I(1) = SXYZ(1,I)
     RXYZ_I(2) = SXYZ(2,I)
     RXYZ_I(3) = SXYZ(3,I)

     FXYZ_I = 0.0

     TI = ITYPE(I)

     include 'BONDS.inc'

     include 'ANGLES.inc'

     include 'TORSIONS.inc'

     include 'OUTOFPLANES.inc'

     FXYZ_L(1,I) = FXYZ_L(1,I) + FXYZ_I(1)
     FXYZ_L(2,I) = FXYZ_L(2,I) + FXYZ_I(2)
     FXYZ_L(3,I) = FXYZ_L(3,I) + FXYZ_I(3)

  END DO
  !$OMP END DO

  !Collate forces from all threads
  DO I=1,NITEMS
     FXYZ(1,I) = FXYZ(1,I) + FXYZ_L(1,I)
     FXYZ(2,I) = FXYZ(2,I) + FXYZ_L(2,I)
     FXYZ(3,I) = FXYZ(3,I) + FXYZ_L(3,I)
  END DO

  !$OMP END PARALLEL

  RETURN

END SUBROUTINE BONDED_FORCE
