SUBROUTINE BONDED_FORCE()

USE VAR

IMPLICIT NONE

INTEGER :: A
INTEGER :: I, J, K, L, TI, TJ, TK, TL, TIJ, TIJK, TIJKL, TOIJKL
INTEGER :: NI
REAL(KIND=RKIND) :: RXI, RYI, RZI
REAL(KIND=RKIND) :: FXI, FYI, FZI
REAL(KIND=RKIND) :: RXIJ, RYIJ, RZIJ, RIJSQ, RIJ
REAL(KIND=RKIND) :: RXKJ, RYKJ, RZKJ, RKJ
REAL(KIND=RKIND) :: RXJK, RYJK, RZJK, RJK, RXKL, RYKL, RZKL, RKL
REAL(KIND=RKIND) :: CJ, THETA, COSM, SINM, COTANM, COSN, SINN, COTANN, COST, SIGNT, PHI
REAL(KIND=RKIND) :: CT, eps, PHI_t
REAL(KIND=RKIND) :: RXM, RYM, RZM, RM, RXN, RYN, RZN, RN, RXS, RYS, RZS
REAL(KIND=RKIND) :: ALPHA, FIJ, VIJ, FIJK, VIJK, FIJKL, VIJKL
REAL(KIND=RKIND) :: FXIJ, FYIJ, FZIJ, FXIJK, FYIJK, FZIJK
REAL(KIND=RKIND) :: FX1, FY1, FZ1, FX4, FY4, FZ4, FX12, FY12, FZ12
REAL(KIND=RKIND) :: RXmN, RYmN, RZmN

!$OMP PARALLEL DO DEFAULT(NONE) SCHEDULE(STATIC,1)&
!$OMP& SHARED(NATOMS,SX,SY,SZ,ITYPE,STEP,R2D)&
!$OMP& SHARED(NBONDS,JBOND,IBONDT,BINB,NDATB,RBOND,BOND_FORCE,BOND_POT)&
!$OMP& SHARED(NIJK,JANGLEIJK,KANGLEIJK,IANGT,BINA,ANGLE,BEND_FORCE,BEND_POT)&
!$OMP& SHARED(NIJKL,JTORIJKL,KTORIJKL,LTORIJKL,ITORT,BINT,NDATT,ANGLE_TOR)&
!$OMP& SHARED(TOR_FORCE,TOR_POT)&
!$OMP& SHARED(NOOPIJKL,JOOPIJKL,KOOPIJKL,LOOPIJKL,IOOPT,BINO,NDATO,ANGLE_OOP)&
!$OMP& SHARED(OOP_FORCE,OOP_POT)&
!$OMP& PRIVATE(A, I, J, K, L, TI, TJ, TK, TL, TIJ, TIJK, TIJKL, TOIJKL, NI)&
!$OMP& PRIVATE(RXI,RYI,RZI,FXI,FYI,FZI)&
!$OMP& PRIVATE(RXIJ,RYIJ,RZIJ,RIJSQ,RIJ)&
!$OMP& PRIVATE(RXKJ, RYKJ, RZKJ, RKJ)&
!$OMP& PRIVATE(RXJK, RYJK, RZJK, RJK, RXKL, RYKL, RZKL, RKL)&
!$OMP& PRIVATE(CJ, THETA, COSM, SINM, COTANM, COSN, SINN, COTANN, COST, SIGNT, PHI)&
!$OMP& PRIVATE(CT, eps, PHI_t)&
!$OMP& PRIVATE(RXM, RYM, RZM, RM, RXN, RYN, RZN, RN, RXS, RYS, RZS)&
!$OMP& PRIVATE(ALPHA, FIJ, VIJ, FIJK, VIJK, FIJKL, VIJKL)&
!$OMP& PRIVATE(FXIJ,FYIJ,FZIJ,FXIJK, FYIJK, FZIJK)&
!$OMP& PRIVATE(FX1, FY1, FZ1, FX4, FY4, FZ4, FX12, FY12, FZ12)&
!$OMP& PRIVATE(RXmN, RYmN, RZmN)&
!$OMP& REDUCTION(+:VBOND,VANGLE,VTOR,VOOP)&
!$OMP& REDUCTION(+:FX,FY,FZ)
DO I=1,NATOMS
   RXI = SX(I)
   RYI = SY(I)
   RZI = SZ(I)

   FXI = 0.0D0 
   FYI = 0.0D0
   FZI = 0.0D0

   TI = ITYPE(I)

   include 'BONDS.inc'

   include 'ANGLES.inc'

   include 'TORSIONS.inc'

   include 'OUTOFPLANES.inc'

   FX(I) = FX(I) + FXI
   FY(I) = FY(I) + FYI
   FZ(I) = FZ(I) + FZI

END DO
!$OMP END PARALLEL DO

RETURN

END SUBROUTINE BONDED_FORCE
