#ifndef DOXY_SKIP
#include "ibi-preprocess.h"
#endif
!> @file
!> @brief Calculate all bonded forces
!!
!> @details Contains, bonds, angles, torsions and out of planes torsions
!! 
!! Called from NEW_FORCE.f90
!!
!> @note Is parallelised using OpenMP

SUBROUTINE BONDED_FORCE()

  USE VAR
  USE OMP_LIB

  IMPLICIT NONE

  INTEGER :: A
  INTEGER :: I, J, K, L, TI, TJ, TK, TL, TIJ, TIJK, TIJKL, TOIJKL
  INTEGER :: NI
  REAL(KIND=RKIND) :: RXI, RYI, RZI
  REAL(KIND=RKIND) :: FXI, FYI, FZI
  REAL(KIND=RKIND) :: RXIJ, RYIJ, RZIJ, RIJSQ, RIJ
  REAL(KIND=RKIND) :: RXKJ, RYKJ, RZKJ, RKJ
  REAL(KIND=RKIND) :: RXJK, RYJK, RZJK, RJK, RXKL, RYKL, RZKL, RKL
  REAL(KIND=RKIND) :: THETA, COSM, SINM, COTANM, COSN, SINN, COTANN, COST, SIGNT, PHI
  REAL(KIND=RKIND) :: CT, eps, PHI_t
  REAL(KIND=RKIND) :: RXM, RYM, RZM, RM, RXN, RYN, RZN, RN, RXS, RYS, RZS
  REAL(KIND=RKIND) :: ALPHA, FIJ, VIJ, FIJK, VIJK, FIJKL, VIJKL
  REAL(KIND=RKIND) :: FXIJ, FYIJ, FZIJ, FXIJK, FYIJK, FZIJK
  REAL(KIND=RKIND) :: FX1, FY1, FZ1, FX4, FY4, FZ4, FX12, FY12, FZ12
  REAL(KIND=RKIND) :: RXmN, RYmN, RZmN
  REAL(KIND=RKIND), DIMENSION(NITEMS) :: FXL, FYL, FZL
#ifdef DETAILED_ATOM
  INTEGER :: SPEC_ATOM = 1837 !Will print out all information on a certain atom to sdout
#endif

#ifdef DETAILED_ATOM
  WRITE(*,*) FX(SPEC_ATOM), FY(SPEC_ATOM), FZ(SPEC_ATOM), 'Start of BONDED'
#endif

  !$OMP PARALLEL DEFAULT(NONE) &
  !$OMP& SHARED(NITEMS,NATOMS,SX,SY,SZ,ITYPE,STEP,R2D)&
  !$OMP& SHARED(NBONDS,JBOND,IBONDT,BINB,NDATB,RBOND,BOND_FORCE,BOND_POT)&
  !$OMP& SHARED(NIJK,JANGLEIJK,KANGLEIJK,IANGT,BINA,ANGLE,BEND_FORCE,BEND_POT)&
  !$OMP& SHARED(NIJKL,JTORIJKL,KTORIJKL,LTORIJKL,ITORT,BINT,NDATT,ANGLE_TOR)&
  !$OMP& SHARED(TOR_FORCE,TOR_POT)&
  !$OMP& SHARED(NOOPIJKL,JOOPIJKL,KOOPIJKL,LOOPIJKL,IOOPT,BINO,NDATO,ANGLE_OOP)&
  !$OMP& SHARED(OOP_FORCE,OOP_POT)&
#ifdef DETAILED_ATOM
  !$OMP& SHARED(SPEC_ATOM)&
#endif
  !$OMP& SHARED(BOND_TYPE_LABEL, ANGLE_TYPE_LABEL)&
  !$OMP& SHARED(TORSION_TYPE_LABEL, OOP_TYPE_LABEL)&
  !$OMP& PRIVATE(A, I, J, K, L, TI, TJ, TK, TL, TIJ, TIJK, TIJKL, NI, TOIJKL)&
  !$OMP& PRIVATE(RXI,RYI,RZI,FXI,FYI,FZI)&
  !$OMP& PRIVATE(RXIJ,RYIJ,RZIJ,RIJSQ,RIJ)&
  !$OMP& PRIVATE(RXKJ, RYKJ, RZKJ, RKJ)&
  !$OMP& PRIVATE(RXJK, RYJK, RZJK, RJK, RXKL, RYKL, RZKL, RKL)&
  !$OMP& PRIVATE(THETA, COSM, SINM, COTANM, COSN, SINN, COTANN, COST, SIGNT, PHI)&
  !$OMP& PRIVATE(CT, eps, PHI_t)&
  !$OMP& PRIVATE(RXM, RYM, RZM, RM, RXN, RYN, RZN, RN, RXS, RYS, RZS)&
  !$OMP& PRIVATE(ALPHA, FIJ, VIJ, FIJK, VIJK, FIJKL, VIJKL)&
  !$OMP& PRIVATE(FXIJ,FYIJ,FZIJ,FXIJK, FYIJK, FZIJK)&
  !$OMP& PRIVATE(FX1, FY1, FZ1, FX4, FY4, FZ4, FX12, FY12, FZ12)&
  !$OMP& PRIVATE(RXmN, RYmN, RZmN)&
  !$OMP& PRIVATE(FXL,FYL,FZL)&
  !$OMP& REDUCTION(+:V_BOND, V_ANGLE, V_TORSION, V_OOP)&
  !$OMP& REDUCTION(+:FX,FY,FZ)

  DO I=1,NITEMS
     FXL(I) = 0.0D0
     FYL(I) = 0.0D0
     FZL(I) = 0.0D0
  END DO

  !$OMP DO SCHEDULE(STATIC,1)
  DO I=1,NITEMS
     RXI = SX(I)
     RYI = SY(I)
     RZI = SZ(I)

     FXI = 0.0D0 
     FYI = 0.0D0
     FZI = 0.0D0

     TI = ITYPE(I)

     include 'BONDS.inc'

     include 'ANGLES.inc'

     include 'TORSIONS.inc'

     include 'OUTOFPLANES.inc'

     FXL(I) = FXL(I) + FXI
     FYL(I) = FYL(I) + FYI
     FZL(I) = FZL(I) + FZI

  END DO
  !$OMP END DO

  !Collate forces from all threads
  DO I=1,NITEMS
     FX(I) = FX(I) + FXL(I)
     FY(I) = FY(I) + FYL(I)
     FZ(I) = FZ(I) + FZL(I)
  END DO

  !$OMP END PARALLEL

#ifdef DETAILED_ATOM
  WRITE(*,*) FX(SPEC_ATOM), FY(SPEC_ATOM), FZ(SPEC_ATOM), 'End of BONDED'
#endif

  RETURN

END SUBROUTINE BONDED_FORCE
