SUBROUTINE DISTRIBUTE_VSFORCE()

  USE VAR

  IMPLICIT NONE

  INTEGER :: I, J, TI, TJ, A, VS_POS

  DO I=1,NVIRTA
     TI = VITYPE(I)
     VS_POS = NATOMS + I
     DO A=1,VIRT_NUMATOMS(TI)
        J = VIRT_ATM_IND(I,A)
        TJ = ITYPE(J)
        FX(J) = FX(J) + FX(VS_POS)*VIRT_MASSCOEFF(TI,TJ)
        FY(J) = FY(J) + FY(VS_POS)*VIRT_MASSCOEFF(TI,TJ)
        FZ(J) = FZ(J) + FZ(VS_POS)*VIRT_MASSCOEFF(TI,TJ)
     END DO
  END DO

  RETURN
END SUBROUTINE DISTRIBUTE_VSFORCE
