!> @file
!> @brief Creates the linked cell lists for neighbour list updates
!> @details Called from UPDATE_NEIGHBOURLIST.f90

SUBROUTINE LINKS(HEAD,MAXNUMCELL,INDEX_LIST,N,CELL,NCELLX, NCELLY, NCELLZ, LCLIST)
  USE VAR
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: MAXNUMCELL, N, INDEX_LIST(N)
  INTEGER, INTENT(IN) :: NCELLX, NCELLY, NCELLZ
  INTEGER, INTENT(INOUT) :: HEAD(MAXNUMCELL), CELL(N), LCLIST(N)
  INTEGER A,I,JCELL

  HEAD = 0
  DO A = 1,N
     I = INDEX_LIST(A)
     JCELL = 1 + INT((RX(I)*BOXXINV + 0.5D0)*NCELLX)*NCELLZ*NCELLY                     &
          + INT((RY(I)*BOXYINV + 0.5D0)*NCELLY)*NCELLZ              &
          + INT((RZ(I)*BOXZINV + 0.5D0)*NCELLZ)
     LCLIST(A) = HEAD(JCELL)
     HEAD(JCELL) = A
     CELL(A) = JCELL

  END DO
  RETURN
END SUBROUTINE LINKS
