SUBROUTINE LINKS(HEAD,MAXNUMCELL,INDEX_LIST,N,CELL,NCELLX, NCELLY, NCELLZ, LCLIST)
  USE VAR
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: MAXNUMCELL, N, INDEX_LIST(N)
  INTEGER, INTENT(IN) :: NCELLX, NCELLY, NCELLZ
  INTEGER, INTENT(INOUT) :: HEAD(MAXNUMCELL), CELL(NITEMS), LCLIST(NITEMS)
  INTEGER A,I,JCELL

  HEAD = 0
  DO A = 1,N
     I = INDEX_LIST(A)
     JCELL = 1 + INT((RX(I)*BOXXINV + 0.5D0)*NCELLX)*NCELLZ*NCELLY                     &
          + INT((RY(I)*BOXYINV + 0.5D0)*NCELLY)*NCELLZ              &
          + INT((RZ(I)*BOXZINV + 0.5D0)*NCELLZ)
     LCLIST(I) = HEAD(JCELL)
     HEAD(JCELL) = I
     CELL(I) = JCELL

  END DO
  RETURN
END SUBROUTINE LINKS
