SUBROUTINE MAKE_LISTS()

USE VAR

IMPLICIT NONE

INTEGER :: I, NUMATOM, NUMBEADVS

NUMATOMS =0
NUMBEADS =0

DO I=1,NATOMS
   IF(TYPE_LABEL(I) .eq. 1) THEN !1 is atom
      NUMATOMS = NUMATOMS +1
   ELSE IF(TYPE_LABEL(I) .eq. 2) THEN!type_label = 2 is bead
      NUMBEADS = NUMBEADS +1
   ELSE
      WRITE(1,*) 'ATOM ',I,' HAS INVALID TYPE LABEL, CHECK interaction FILE'
      WRITE(*,*) 'ATOM ',I,' HAS INVALID TYPE LABEL, CHECK interaction FILE'
      ISTOP = 1
      RETURN
   END IF
END DO

NCOARSE = NUMBEADS + NVIRTA
ALLOCATE( ATOM(NUMATOMS) &
     , BEAD(NCOARSE) )

ATOM = 0
BEAD = 0
NUMATOM =0 
NUMBEADVS =0

!Make atom list
DO I=1,NATOMS
   IF(type_label(I) .eq. 1) then !If atom
      NUMATOM = NUMATOM +1      
      ATOM(NUMATOM) = I
   ELSE
      NUMBEADVS = NUMBEADVS +1
      BEAD(NUMBEADVS) = I
   END IF
END DO

DO I=1,NVIRTA
   NUMBEADVS = NUMBEADVS +1
   BEAD(NUMBEADVS) = NATOMS+I
END DO

RETURN

END SUBROUTINE MAKE_LISTS
