#include "ibi-preprocess.h"

!	******************************************************************
!	NATOMS		TOTAL NUMBER OF ATOMS
!	NSTEP		NUMBER OF TIME STEP
!	NMOL		TOTAL NUMBER OF MOLECULES
!	NATM()		NUMBER OF ATOMS IN EACH MOLECULES
!	ITYPE()		TYPE OF EACH ATOMS
!	NBONDS()	NUMBER OF BOND FOR EACH ATOME
!	JBOND(,)	INDEX OF BONDED ATOMS TO EACH ATOMS
!	NIJK()		NUMBER OF IJK ANGLES THAT ATOM I BELONGS TO THEM
!	NIJKL()		NUMBER OF IJKL TORSIONS THAT ATOM I BELONGS TO THEM
!	NTYPE		NUMBER OF DIFFRENT ATOM TYPES
!	NBTYPE		NUMBER OF DIFFRENT TYPES OF BONDS
!	NATYPE		NUMBER OF DIFFRENT TYPES OF ANGLES
!	NTTYPE		NUMBER OF DIFFRENT TYPES OF TORSIONS
!	TEMP		TEMPERATURE
!	TAUT		COUPLING TIME FOR TEMPERATURE
!	TAUP		COUPLING TIME FOR PRESSURE
!	MASS		MASS OF DIFFRENT ATOM TYPES
!	LABEL		NAME OF DIFFRENT ATOM TYPES

MODULE VAR



INTEGER*4 :: ENSEMBLE, NATOMS, NITEMS, NCOARSE, NSTEP, NMOL, MAXINPUT,PPF_INPUT,LAINPUT,DPDINPUT,WDPDT
INTEGER*4 :: INTERACT, NAVERAGE, HALT_DRIFT, NTRJ, NSAMPLING
INTEGER*4 :: NFRAME, NUPDATE , NDATA, VUPDATE
INTEGER :: NONBEXC_ATOM, NONBEXC_BEAD
INTEGER :: NOTORS=0, NOANGLE = 0, VIRTSITE,NVIRTA = 0, IBRDESCR
INTEGER,PARAMETER :: RKIND = 8
INTEGER :: IOSTAT, IOS, ISTOP, IOS2, RESTART,TSET

INTEGER :: NTYPE, NBTYPE, NNBTYPE, NATYPE, NTTYPE, NOTYPE
INTEGER :: STEP
INTEGER:: IRAV, NRAV, LIMRAV, IAVP, LIMAVP

REAL(KIND=RKIND) :: E_ATOM, E_MIX, E_CG

INTEGER:: NCELLX_ATOM, NCELLY_ATOM, NCELLZ_ATOM
INTEGER:: NCELLX_BEAD, NCELLY_BEAD, NCELLZ_BEAD
INTEGER:: NUMCELL_ATOM, MAPSIZE_ATOM, MAXNUMCELL_ATOM, MAXMAPSIZE_ATOM
INTEGER:: NUMCELL_BEAD, MAPSIZE_BEAD, MAXNUMCELL_BEAD, MAXMAPSIZE_BEAD
INTEGER :: SLIDE,SLIDE2,AVT
INTEGER, PARAMETER :: MAXCONNECTIONS = 20 !Maximum number of things it is connected into	
PARAMETER ( MAXINPUT = 200000, NDATA = 20000 )
PARAMETER ( LIMRAV = 100, LIMAVP = 10)
!       PARAMETER ( SLIDE2 = SLIDE/2 )
INTEGER, POINTER :: IBONDT(:,:), INBONDT(:,:), IANGT(:,:,:)
INTEGER, POINTER :: ITORT(:,:,:,:), IOOPT(:,:,:,:)
INTEGER, POINTER :: JANGLEIJK(:,:), KANGLEIJK(:,:)
INTEGER, POINTER :: NOJANGLEIJK(:,:), NOKANGLEIJK(:,:) 
INTEGER, POINTER :: FJTORIJKL(:,:), FKTORIJKL(:,:), FLTORIJKL(:,:)
INTEGER, POINTER :: JTORIJKL(:,:), KTORIJKL(:,:), LTORIJKL(:,:)
INTEGER, POINTER :: JOOPIJKL(:,:), KOOPIJKL(:,:), LOOPIJKL(:,:)

INTEGER, POINTER :: VIRT_POINT(:), VLIST(:), VLIST_SEC(:),VIRT_POINT_SEC(:)

INTEGER :: MAXNAB_ATOM
INTEGER :: MAXNAB_BEAD
INTEGER :: MAX_CONTACT!Largest gap between 2 connected things

INTEGER, POINTER :: CONNECTIONS(:), CONNECTED_TO(:,:)

#ifdef TIMING_ON
REAL*8, DIMENSION(2) :: t_LOOP 
REAL*8, DIMENSION(2) :: t_FORCECALC
REAL*8, DIMENSION(2) :: t_VIRTUAL_DEF, t_UPDATE_NEIGHBOURLIST
REAL*8, DIMENSION(2) :: t_MAPS_atom, t_MAPS_bead, t_LINKS_atom, t_LINKS_bead
REAL*8, DIMENSION(2) :: t_NEW_NEIGHBOUR_atom, t_NEW_NEIGHBOUR_bead
REAL*8, DIMENSION(2) :: t_NEW_FORCE, t_NONBONDED_atom, t_NONBONDED_bead, t_DISTRIBUTE_VSFORCE
REAL*8, DIMENSION(2) :: t_BONDED_FORCE, t_BONDS, t_ANGLES, t_TORSIONS, t_OUTOFPLANES
REAL*8, DIMENSION(2) :: t_SHIFT, t_MOVE, t_MOMENTUM, t_SCALEBP
REAL*8, DIMENSION(2) :: t_REPORTRESULTS, t_AVERAGE, t_WRITETRJ, t_OUTPUT
#endif

INTEGER, POINTER :: POINT_ATOM(:), LIST_ATOM(:)
INTEGER, POINTER :: POINT_BEAD(:), LIST_BEAD(:)

INTEGER, POINTER :: CELL_ATOM(:), NCELL_ATOM(:), MAP_ATOM(:),LCLIST_ATOM(:),HEAD_ATOM(:),INDX_ATOM(:,:)
INTEGER, POINTER :: CELL_BEAD(:), NCELL_BEAD(:), MAP_BEAD(:),LCLIST_BEAD(:),HEAD_BEAD(:),INDX_BEAD(:,:)

INTEGER, POINTER :: VLCLIST(:),VHEAD(:), VCELL(:), INDEX_VSITE(:), VITYPE(:)

INTEGER, POINTER :: NATM(:), ITYPE(:), JBOND(:,:)
INTEGER :: NONBOND
INTEGER, POINTER :: NBONDS(:), NIJK(:), NIJKL(:), NOOPIJKL(:)
INTEGER, POINTER :: ATIANG(:)                                           !RECORD TYPE OF ATOMS WHICH HAS ANGLE INTERACTIONS
INTEGER, POINTER :: Z_POSITION(:)
INTEGER, POINTER :: NOANGLEIJK(:),FNIJKL(:) 
INTEGER, POINTER :: TYPE_LABEL(:), INDEX_BEAD(:,:),TYPE_BEAD(:)
INTEGER, POINTER :: COMVECT(:), COMPCOM(:,:),TYPECOM(:)
INTEGER, POINTER :: NDATB(:),NDATAN(:),NDATT(:),NDATNB(:), NDATO(:)

REAL(KIND=RKIND) :: RLIST_ATOM, RLISTSQ_ATOM, RCUT_ATOM, RCUTSQ_ATOM
REAL(KIND=RKIND) :: RLIST_BEAD, RLISTSQ_BEAD, RCUT_BEAD, RCUTSQ_BEAD

REAL(KIND=RKIND) :: KB, NA
PARAMETER ( NA = 6.0221367D+23 ,KB = 1.380658D-23)

REAL*8 :: MMOLY, MASSSCALE, RSCALE, ESCALE,VISCOSITY,RVISCOSITY
REAL*8 :: TEMP0, DT0, TAUT0, TAUP0, PRESSURE0, INITIME,RCUTDPD
REAL*8 :: MKTEMP, VOLUME, INV_VOLUME
REAL*8 :: TEMP, DT, TAUT, TAUP, PRESSURE, TIN, DT2, DTSQ2
REAL*8 :: TEMPSCALE, PSCALE, TIMESCALE, FSCALE, DSCALE, VSCALE
REAL*8 :: BOXX, BOXY, BOXZ, BOXXINV, BOXYINV, BOXZINV, TOTMASS
REAL*8 :: R2D, D2R, FAC, CONV, BOXX2, BOXY2, BOXZ2
REAL*8 :: VBOND, VANGLE
REAL(KIND=RKIND) :: VNBOND_ATOM, VBOND_ATOM, VANGLE_ATOM, VTOR, VNBOND_TOTAL
REAL(KIND=RKIND) :: VNBOND_BEAD, VBOND_BEAD, VANGLE_BEAD
REAL(KIND=RKIND) :: VNBOND_MIX, VNBOND_MIX2
REAL(KIND=RKIND) ::  TEK
REAL*8 :: VOOP
REAL*8 :: TVNBOND, TVBOND, TVANGLE, TVTOR
REAL*8 :: BETA, BETA0, PFAC, CM
REAL*8 :: PT23, PT11, PT22, PT33, PT13, PT12
REAL*8 :: LX, LY, LZ, EK
REAL*8 :: RPT33, RPT12, RPT13, RVTOR, RVANGLE
REAL*8 :: RVOOP
REAL*8 :: RDENS, RVOL, RBOXZ, RBOXY, RBOXX, RPT11, RPT22
REAL*8 :: RPT23, RP, RTEMP, RE, RV, REK, RVBOND, RVNBOND
REAL*8 :: EXTER_FX,LAFREQ,DEN1,DEN2,RDEN1,RDEN2,RV_AVE1,RV_AVE2
REAL*8 :: rfac, sigma,gamma,VVCONST,VVCONST0
REAL*8, POINTER :: VIRTRX(:), VIRTRY(:),VIRTRZ(:)
REAL*8, POINTER :: RX(:), RY(:), RZ(:), VX(:), VY(:), VZ(:)
REAL*8, POINTER :: VTX(:),VTY(:),VTZ(:),VOX(:),VOY(:),VOZ(:)
REAL*8, allocatable :: FX(:), FY(:), FZ(:)
REAL*8, allocatable ::  FXNB(:), FYNB(:), FZNB(:)
REAL(KIND=RKIND), allocatable :: VFXNB(:), VFYNB(:), VFZNB(:)
REAL*8, POINTER :: RBOND(:,:), BOND_FORCE(:,:), BOND_POT(:,:) 
REAL*8, POINTER :: RNBOND(:,:), NBOND_FORCE(:,:), NBOND_POT(:,:) 
REAL*8, POINTER :: ANGLE(:,:), BEND_FORCE(:,:), BEND_POT(:,:)
REAL*8, POINTER :: ANGLE_TOR(:,:), TOR_FORCE(:,:), TOR_POT(:,:)
REAL*8, POINTER :: ANGLE_OOP(:,:), OOP_FORCE(:,:), OOP_POT(:,:)
REAL*8, POINTER :: MASS(:), INVMASS(:), MASS0(:), BINNB(:), BINB(:), BINA(:),BEADMASS(:)
REAL*8, POINTER :: GB(:,:), GA(:,:), LB(:), LA(:), BINT(:)
REAL*8, POINTER :: SX(:), SY(:), SZ(:), BINO(:)
REAL*8, POINTER :: STEK(:), STVBOND(:), STVNBOND(:), STVTOR(:), STVOOP(:)
REAL*8, POINTER :: STVANGLE(:), STV(:), STPT12(:)
REAL*8, POINTER :: STE(:), STEMP(:), STPT11(:), STPT22(:), STPT33(:)
REAL*8, POINTER :: STPT13(:), STPT23(:), STP(:), SP(:)
REAL*8, POINTER :: SBOXX(:), SBOXY(:), SBOXZ(:), SVOL(:), SDENS(:)
REAL*8, POINTER :: NUM(:),DENSITY(:),TEEMP(:),VXPRO(:),VPX(:)
REAL*8, POINTER :: RVXPRO(:),RDENSITY(:),RTEEMP(:),PZX(:),RPZX(:)
REAL*8, POINTER :: VVISCOSITY(:),RVVISCOSITY(:)
REAL(KIND=RKIND), POINTER ::  TOTBMASS(:),INVTOTBMASS(:) 
  REAL(KIND=RKIND),PARAMETER :: PI= 3.141592653589793238462643383279
       
    ! Variables for DPD 
REAL*8 TFAC
INTEGER DPD_BONDED
INTEGER, POINTER :: DPDLIST(:),DPDPOINT(:)
REAL*8, POINTER ::  VXO(:),  VYO(:), VZO(:)
!INTEGER, POINTER :: VDPDLIST(:),VDPDPOINT(:)
!       REAL*8  BETAT 

!     Variables for Hybrid Description
INTEGER :: NUM_BEAD = 0,timestepcheck,nonbondvirt, NUM_VS = 0, NUM_BA=0
INTEGER :: NB
integer :: contactB=0, contactA=0
INTEGER,POINTER :: INDEX_AB(:),virtNmol(:)
INTEGER, POINTER :: VIRT_NUMATOMS(:), VIRT_CENTER(:), VIRT_VS_IND(:), VIRT_ATM_IND(:,:)
REAL(KIND=RKIND), POINTER :: VIRT_MASS(:), VIRT_INVMASS(:), VIRT_MASSCOEFF(:,:)
real(kind=rkind) :: FCUTA,FCUTB
real(kind=rkind) :: VBOND_MIX, VANGLE_MIX, VTOR_MIX, VOOP_MIX
real(kind=rkind) :: VNBOND_CG, VBOND_CG, VANGLE_CG, VTOR_CG, VOOP_CG
real(kind=rkind) :: RVBOND_MIX, RVANGLE_MIX, RVTOR_MIX, RVOOP_MIX, RVNBOND_MIX
real(kind=rkind) :: RVNBOND_CG, RVBOND_CG, RVANGLE_CG, RVTOR_CG, RVOOP_CG
real(kind=rkind) :: RVBOND_At, RVANGLE_At, RVTOR_At, RVOOP_At, RVNBOND_At
REAL(kind=rkind), POINTER :: STVBOND_MIX(:), STVNBOND_MIX(:), STVTOR_MIX(:), STVOOP_MIX(:)
REAL(kind=rkind), POINTER :: STVANGLE_MIX(:), STV_MIX(:)
REAL(kind=rkind), POINTER :: STVBOND_CG(:), STVNBOND_CG(:), STVTOR_CG(:), STVOOP_CG(:)
REAL(kind=rkind), POINTER :: STVANGLE_CG(:), STV_CG(:)
REAL(kind=rkind), POINTER :: STVBOND_At(:), STVNBOND_At(:), STVTOR_At(:), STVOOP_At(:)
REAL(kind=rkind), POINTER :: STVANGLE_At(:), STV_At(:)
 character(len=18) :: name_file_virt
 character(len=7),pointer  :: name_mol(:) 
 character(len=2),dimension(18) :: name_label='NU'  
INTEGER :: NUMATOMS, NUMBEADS
INTEGER, POINTER :: ATOM(:), BEAD(:)

#ifdef DEBUG_OOP
!     Variables for Testing the OOP with the Atomistic PolyStyrene
REAL*8 :: VOOP_ring,VOOP_LD,VOOP_L,VOOP_D
#endif



!     Variables for MTS
INTEGER :: MTS_CHECK,type_mts,I0,I1,I2,I3,I4,I5,MTSPARAM2,TSMTS,MTSPARAM,Kmts
reaL(KIND=RKIND) :: idt,idt2,idt3,idt4,idt5,mtsdt2,dt3,dt4,dt5
REAL(KIND=RKIND),POINTER :: FXi0(:),FYi0(:),FZi0(:) 
REAL(KIND=RKIND),POINTER :: FXi1(:),FYi1(:),FZi1(:) 
REAL(KIND=RKIND),POINTER :: FXii(:),FYii(:),FZii(:) 
REAL(KIND=RKIND),POINTER :: FXiii(:),FYiii(:),FZiii(:) 
REAL(KIND=RKIND),POINTER :: FXiiii(:),FYiiii(:),FZiiii(:) 
REAL(KIND=RKIND),POINTER :: FXv(:),FYv(:),FZv(:) 
REAL(KIND=RKIND),POINTER :: FXprova(:),FYprova(:),FZprova(:) 

!    Variables for SHAKE

integer,parameter :: maxit=200
real(kind=rkind),parameter :: tol=1.0E-10,rptol=1.0E-6
real(kind=rkind),pointer :: constr(:)
logical :: noBond,shakeOK
logical,pointer :: typeBond(:)


!***************************************

 CHARACTER(80), POINTER :: LABEL(:)
 CHARACTER(72) :: TITLE, NEIGHBORLIST
 CHARACTER(len=2):: TYn
 CHARACTER(1) day(9)
 INTEGER :: iseed       !for RANDOM NUMBER generator
        END MODULE VAR
!    *******************************************************************
!    *******************************************************************
