#ifndef DOXY_SKIP
#include "ibi-preprocess.h"
#endif
!*MODULE VAR

!> @brief Contains all the global variables throughout the program


MODULE VAR

  INTEGER,PARAMETER :: RKIND = 8
  !UNIT CONSTANTS
  REAL(KIND=RKIND), PARAMETER :: KB = 1.380658D-23
  REAL(KIND=RKIND), PARAMETER :: NA = 6.0221367D+23
  REAL(KIND=RKIND), PARAMETER :: PI = 3.141592653589793238462643383279

  !These are called in WRITETRJ (binary file!) so need to remain strictly as these types
  INTEGER*4 :: NFRAME, NTRJ, NATOMS
  REAL*8, DIMENSION(2) :: EK
  !End WRITETRJ stuff
  INTEGER*4 :: ENSEMBLE, NITEMS, NCOARSE, NSTEP, NMOL, MAXINPUT,PPF_INPUT,LAINPUT,DPDINPUT,WDPDT
  INTEGER*4 :: INTERACT, NAVERAGE, HALT_DRIFT, NSAMPLING
  INTEGER*4 :: NUPDATE , NDATA, VUPDATE

  INTEGER :: NONBEXC_ATOM, NONBEXC_BEAD
  INTEGER :: NOTORS=0, NOANGLE = 0, VIRTSITE,NVIRTA = 0, IBRDESCR
  INTEGER :: IOSTAT, IOS, ISTOP, IOS2, RESTART,TSET

  INTEGER :: NTYPE, NBTYPE, NNBTYPE, NATYPE, NTTYPE, NOTYPE
  INTEGER :: STEP
  INTEGER :: IRAV, NRAV, LIMRAV, IAVP, LIMAVP

  INTEGER:: NCELLX_ATOM, NCELLY_ATOM, NCELLZ_ATOM
  INTEGER:: NCELLX_BEAD, NCELLY_BEAD, NCELLZ_BEAD
  INTEGER:: NUMCELL_ATOM, MAPSIZE_ATOM, MAXNUMCELL_ATOM, MAXMAPSIZE_ATOM
  INTEGER:: NUMCELL_BEAD, MAPSIZE_BEAD, MAXNUMCELL_BEAD, MAXMAPSIZE_BEAD
  INTEGER :: SLIDE,SLIDE2,AVT
  INTEGER, PARAMETER :: MAXCONNECTIONS = 20 !Maximum number of things it is connected into	
  PARAMETER ( MAXINPUT = 100000, NDATA = 20000 )
  PARAMETER ( LIMRAV = 100, LIMAVP = 10)
  !       PARAMETER ( SLIDE2 = SLIDE/2 )
  INTEGER, POINTER :: IBONDT(:,:), INBONDT(:,:), IANGT(:,:,:)
  INTEGER, POINTER :: ITORT(:,:,:,:), IOOPT(:,:,:,:)
  INTEGER, POINTER :: JANGLEIJK(:,:), KANGLEIJK(:,:)
  INTEGER, POINTER :: NOJANGLEIJK(:,:), NOKANGLEIJK(:,:) 
  INTEGER, POINTER :: FJTORIJKL(:,:), FKTORIJKL(:,:), FLTORIJKL(:,:)
  INTEGER, POINTER :: JTORIJKL(:,:), KTORIJKL(:,:), LTORIJKL(:,:)
  INTEGER, POINTER :: JOOPIJKL(:,:), KOOPIJKL(:,:), LOOPIJKL(:,:)
  INTEGER, ALLOCATABLE, DIMENSION(:) :: BOND_TYPE_LABEL, ANGLE_TYPE_LABEL
  INTEGER, ALLOCATABLE, DIMENSION(:) :: TORSION_TYPE_LABEL, OOP_TYPE_LABEL 

  INTEGER, POINTER :: VIRT_POINT(:), VLIST(:), VLIST_SEC(:),VIRT_POINT_SEC(:)

  INTEGER :: MAXNAB_ATOM
  INTEGER :: MAXNAB_BEAD
  INTEGER :: MAX_CONTACT!Largest gap between 2 connected things

  INTEGER, POINTER :: CONNECTIONS(:), CONNECTED_TO(:,:)

  !Timing variables
  REAL*8, DIMENSION(2) :: t_LOOP 
  REAL*8, DIMENSION(2) :: t_FORCECALC
  REAL*8, DIMENSION(2) :: t_VIRTUAL_DEF, t_UPDATE_NEIGHBOURLIST
  REAL*8, DIMENSION(2) :: t_MAPS_atom, t_MAPS_bead, t_LINKS_atom, t_LINKS_bead
  REAL*8, DIMENSION(2) :: t_NEW_NEIGHBOUR_atom, t_NEW_NEIGHBOUR_bead
  REAL*8, DIMENSION(2) :: t_NEW_FORCE, t_NONBONDED_atom, t_NONBONDED_bead, t_DISTRIBUTE_VSFORCE
  REAL*8, DIMENSION(2) :: t_BONDED_FORCE, t_BONDS, t_ANGLES, t_TORSIONS, t_OUTOFPLANES
  REAL*8, DIMENSION(2) :: t_SHIFT, t_MOVE, t_MOMENTUM, t_SCALEBP
  REAL*8, DIMENSION(2) :: t_REPORTRESULTS, t_AVERAGE, t_WRITETRJ, t_OUTPUT
  !End timing variables

  !Averaging and output variables
  REAL*8 :: POT_E, TOT_E, PRES(7), BOX(4), DENS
  REAL*8 :: AV_POT_E, AV_TOT_E, AV_PRES(7), AV_BOX(4), AV_DENS
  REAL*8, DIMENSION(3) :: AV_V_NB, AV_V_BOND, AV_V_ANGLE, AV_V_TORSION, AV_V_OOP
  REAL*8, DIMENSION(3) :: AV_TEMP, KIN_E, AV_KIN_E
  !End averaging and output variables

  INTEGER, POINTER :: LIST_ATOM(:,:)
  INTEGER, POINTER :: LIST_BEAD(:,:)

  INTEGER, POINTER :: CELL_ATOM(:), NCELL_ATOM(:), MAP_ATOM(:),LCLIST_ATOM(:),HEAD_ATOM(:),INDX_ATOM(:,:)
  INTEGER, POINTER :: CELL_BEAD(:), NCELL_BEAD(:), MAP_BEAD(:),LCLIST_BEAD(:),HEAD_BEAD(:),INDX_BEAD(:,:)

  INTEGER, POINTER :: VLCLIST(:),VHEAD(:), VCELL(:), INDEX_VSITE(:), VITYPE(:)

  INTEGER, POINTER :: NATM(:), ITYPE(:), JBOND(:,:)
  INTEGER :: NONBOND
  INTEGER, POINTER :: NBONDS(:), NIJK(:), NIJKL(:), NOOPIJKL(:)
  INTEGER, POINTER :: ATIANG(:)                                           !RECORD TYPE OF ATOMS WHICH HAS ANGLE INTERACTIONS
  INTEGER, POINTER :: NOANGLEIJK(:),FNIJKL(:) 
  INTEGER, POINTER :: TYPE_LABEL(:), INDEX_BEAD(:,:),TYPE_BEAD(:)
  INTEGER, POINTER :: COMVECT(:), COMPCOM(:,:),TYPECOM(:)
  INTEGER, POINTER :: NDATB(:),NDATAN(:),NDATT(:),NDATNB(:), NDATO(:)

  REAL(KIND=RKIND) :: RLIST_ATOM, RLISTSQ_ATOM, RCUT_ATOM, RCUTSQ_ATOM
  REAL(KIND=RKIND) :: RLIST_BEAD, RLISTSQ_BEAD, RCUT_BEAD, RCUTSQ_BEAD

  REAL(KIND=RKIND) :: MMOLY, MASSSCALE, RSCALE, ESCALE,VISCOSITY,RVISCOSITY
  REAL(KIND=RKIND) :: TEMP0, DT0, TAUT0, TAUP0, PRESSURE0, INITIME,RCUTDPD
  REAL(KIND=RKIND) :: MKTEMP, MKTEMP_ATOM, MKTEMP_BEAD
  REAL(KIND=RKIND) :: VOLUME, INV_VOLUME
  REAL(KIND=RKIND) :: TEMP, TEMP_ATOM, TEMP_BEAD
  REAL(KIND=RKIND) :: DT, TAUT, TAUP, PRESSURE, TIN, DT2, DTSQ2
  REAL(KIND=RKIND) :: TEMPSCALE, PSCALE, TIMESCALE, FSCALE, DSCALE, VSCALE
  REAL(KIND=RKIND) :: BOXX, BOXY, BOXZ, BOXXINV, BOXYINV, BOXZINV, TOTMASS
  REAL(KIND=RKIND) :: R2D, D2R, FAC, CONV, BOXX2, BOXY2, BOXZ2
  REAL(KIND=RKIND), DIMENSION(3) :: V_BOND, V_ANGLE, V_TORSION, V_OOP, V_NB
  REAL(KIND=RKIND) :: BETA, BETA0, PFAC, CM
  REAL(KIND=RKIND) :: PT23, PT11, PT22, PT33, PT13, PT12
  REAL(KIND=RKIND) :: LX, LY, LZ
  REAL(KIND=RKIND) :: EXTER_FX,LAFREQ,DEN1,DEN2,RDEN1,RDEN2,RV_AVE1,RV_AVE2
  REAL(KIND=RKIND) :: rfac, sigma,gamma,VVCONST,VVCONST0
  REAL(KIND=RKIND), POINTER :: RX(:), RY(:), RZ(:), VX(:), VY(:), VZ(:)
  REAL(KIND=RKIND), POINTER :: VTX(:),VTY(:),VTZ(:) !move.f90
  REAL(KIND=RKIND), allocatable :: FX(:), FY(:), FZ(:)
  REAL(KIND=RKIND), allocatable :: FXNB(:), FYNB(:), FZNB(:) !for pressure calcs
  REAL(KIND=RKIND), POINTER :: RBOND(:,:), BOND_FORCE(:,:), BOND_POT(:,:) 
  REAL(KIND=RKIND), POINTER :: RNBOND(:,:), NBOND_FORCE(:,:), NBOND_POT(:,:) 
  REAL(KIND=RKIND), POINTER :: ANGLE(:,:), BEND_FORCE(:,:), BEND_POT(:,:)
  REAL(KIND=RKIND), POINTER :: ANGLE_TOR(:,:), TOR_FORCE(:,:), TOR_POT(:,:)
  REAL(KIND=RKIND), POINTER :: ANGLE_OOP(:,:), OOP_FORCE(:,:), OOP_POT(:,:)
  REAL(KIND=RKIND), POINTER :: MASS(:), INVMASS(:), MASS0(:), BINNB(:), BINB(:), BINA(:),BEADMASS(:)
  REAL(KIND=RKIND), POINTER :: GB(:,:), GA(:,:), LB(:), LA(:), BINT(:)
  REAL(KIND=RKIND), POINTER :: SX(:), SY(:), SZ(:), BINO(:)
  REAL(KIND=RKIND), POINTER :: SP(:)
  REAL(KIND=RKIND), POINTER :: VVISCOSITY(:),RVVISCOSITY(:)
  REAL(KIND=RKIND), POINTER ::  TOTBMASS(:),INVTOTBMASS(:) 

  ! Variables for DPD 
  REAL(KIND=RKIND) TFAC
  INTEGER DPD_BONDED
  INTEGER, POINTER :: DPDLIST(:),DPDPOINT(:)
  REAL(KIND=RKIND), POINTER ::  VXO(:),  VYO(:), VZO(:)
  !INTEGER, POINTER :: VDPDLIST(:),VDPDPOINT(:)
  !       REAL(KIND=RKIND)  BETAT 

  !     Variables for Hybrid Description
  INTEGER :: NUM_BEAD = 0,timestepcheck,nonbondvirt
  INTEGER :: NB
  integer :: contactB=0, contactA=0
  INTEGER,POINTER :: INDEX_AB(:),virtNmol(:)
  INTEGER, POINTER :: VIRT_NUMATOMS(:), VIRT_CENTER(:), VIRT_VS_IND(:), VIRT_ATM_IND(:,:)
  REAL(KIND=RKIND), POINTER :: VIRT_MASS(:), VIRT_INVMASS(:), VIRT_MASSCOEFF(:,:)
  real(kind=rkind) :: FCUTA,FCUTB
  character(len=18) :: name_file_virt
  character(len=7),pointer  :: name_mol(:)
  INTEGER, ALLOCATABLE :: MOL(:)
  character(len=2),dimension(18) :: name_label='NU'  
  INTEGER :: NUMATOMS, NUMBEADS
  INTEGER, POINTER :: ATOM(:), BEAD(:)

#ifdef DEBUG_OOP
  !     Variables for Testing the OOP with the Atomistic PolyStyrene
  REAL(KIND=RKIND) :: VOOP_ring,VOOP_LD,VOOP_L,VOOP_D
#endif



  !     Variables for MTS
  INTEGER :: MTS_CHECK,type_mts,I0,I1,I2,I3,I4,I5,MTSPARAM2,TSMTS,MTSPARAM,Kmts
  reaL(KIND=RKIND) :: idt,idt2,idt3,idt4,idt5,mtsdt2,dt3,dt4,dt5
  REAL(KIND=RKIND),POINTER :: FXi0(:),FYi0(:),FZi0(:) 
  REAL(KIND=RKIND),POINTER :: FXi1(:),FYi1(:),FZi1(:) 
  REAL(KIND=RKIND),POINTER :: FXii(:),FYii(:),FZii(:) 
  REAL(KIND=RKIND),POINTER :: FXiii(:),FYiii(:),FZiii(:) 
  REAL(KIND=RKIND),POINTER :: FXiiii(:),FYiiii(:),FZiiii(:) 
  REAL(KIND=RKIND),POINTER :: FXv(:),FYv(:),FZv(:) 
  REAL(KIND=RKIND),POINTER :: FXprova(:),FYprova(:),FZprova(:) 

  !    Variables for SHAKE

  integer,parameter :: maxit=200
  real(kind=rkind),parameter :: tol=1.0E-10,rptol=1.0E-6
  real(kind=rkind),pointer :: constr(:)
  logical :: noBond,shakeOK
  logical,pointer :: typeBond(:)


  !***************************************

  CHARACTER(6), POINTER :: LABEL(:)
  CHARACTER(72) :: TITLE, NEIGHBORLIST
  CHARACTER(len=2):: TYn
  CHARACTER(1) day(9)
  INTEGER :: iseed       !for RANDOM NUMBER generator
END MODULE VAR
