          
      MODULE PAIR
      !       VARIABLE FOR STANDARD DPD THERMOSTAT
      INTEGER :: STANDARD_DPDINPUT ! STANDARD_DPDINPUT, 1= use standard DPD,  0 = do not use it  
      INTEGER :: SELFLIST  ! NUMBER RECORD PAIR INTERACTION 
      INTEGER :: NITER     ! NUMBER OF DRAG FORCE ITERATIN 
      INTEGER :: NINIT     !NUMBER OF  STEPS DO WE SCALE THE TEMPERATURE
      INTEGER :: WEIGHT_TYPE  !( WEIGHT FUNCTION TYPE, 1= LINEAR WEIGHT FUNCTION, 2= RECTANGLE WEIGHT FUNCTION)
      !       REAL*8 	 SIGMA  	 ! NOISE STRENGTH 
      !       REAL*8	GAMMA    ! FRICTION CONSTANT
      REAL*8 :: SIGMAT
      REAL*8 :: ITER1, ITER2
      REAL*8, POINTER ::  FDX(:), FDY(:),FDZ(:)  ! DRAG FORCE
      REAL*8, POINTER ::  FRANDOMX(:), FRANDOMY(:), FRANDOMZ(:)  ! RANDOM FORCE
      END MODULE  PAIR 
