#include "ibi-preprocess.h"

MODULE VAR

INTEGER :: revno !Stores the revision number according to bazaar. Read from 'revno' in the same directory
                 !This should be automatically created when you do commits (if you have the plugin installed)
!These are called in WRITETRJ (binary file!) so need to remain strictly as these types
INTEGER*4 :: NFRAME, NTRJ, NATOMS
REAL*8 :: EK
!End WRITETRJ stuff
INTEGER*4 :: ENSEMBLE, NITEMS, NCOARSE, NSTEP, NMOL, MAXINPUT,PPF_INPUT,LAINPUT,DPDINPUT,WDPDT
INTEGER*4 :: INTERACT, NAVERAGE, HALT_DRIFT, NSAMPLING
INTEGER*4 :: NUPDATE , NDATA, VUPDATE

INTEGER :: NONBEXC_ATOM, NONBEXC_BEAD
INTEGER :: NOTORS=0, NOANGLE = 0, VIRTSITE,NVIRTA = 0, IBRDESCR
INTEGER,PARAMETER :: RKIND = 8
INTEGER :: IOSTAT, IOS, ISTOP, IOS2, RESTART,TSET

INTEGER :: NTYPE, NBTYPE, NNBTYPE, NATYPE, NTTYPE, NOTYPE
INTEGER :: STEP
INTEGER:: IRAV, NRAV, LIMRAV, IAVP, LIMAVP

REAL(KIND=RKIND) :: E_ATOM, E_MIX, E_CG

INTEGER:: NCELLX_ATOM, NCELLY_ATOM, NCELLZ_ATOM
INTEGER:: NCELLX_BEAD, NCELLY_BEAD, NCELLZ_BEAD
INTEGER:: NUMCELL_ATOM, MAPSIZE_ATOM, MAXNUMCELL_ATOM, MAXMAPSIZE_ATOM
INTEGER:: NUMCELL_BEAD, MAPSIZE_BEAD, MAXNUMCELL_BEAD, MAXMAPSIZE_BEAD
INTEGER :: SLIDE,SLIDE2,AVT
INTEGER, PARAMETER :: MAXCONNECTIONS = 20 !Maximum number of things it is connected into	
PARAMETER ( MAXINPUT = 200000, NDATA = 20000 )
PARAMETER ( LIMRAV = 100, LIMAVP = 10)
!       PARAMETER ( SLIDE2 = SLIDE/2 )
INTEGER, POINTER :: IBONDT(:,:), INBONDT(:,:), IANGT(:,:,:)
INTEGER, POINTER :: ITORT(:,:,:,:), IOOPT(:,:,:,:)
INTEGER, POINTER :: JANGLEIJK(:,:), KANGLEIJK(:,:)
INTEGER, POINTER :: NOJANGLEIJK(:,:), NOKANGLEIJK(:,:) 
INTEGER, POINTER :: FJTORIJKL(:,:), FKTORIJKL(:,:), FLTORIJKL(:,:)
INTEGER, POINTER :: JTORIJKL(:,:), KTORIJKL(:,:), LTORIJKL(:,:)
INTEGER, POINTER :: JOOPIJKL(:,:), KOOPIJKL(:,:), LOOPIJKL(:,:)

INTEGER, POINTER :: VIRT_POINT(:), VLIST(:), VLIST_SEC(:),VIRT_POINT_SEC(:)

INTEGER :: MAXNAB_ATOM
INTEGER :: MAXNAB_BEAD
INTEGER :: MAX_CONTACT!Largest gap between 2 connected things

INTEGER, POINTER :: CONNECTIONS(:), CONNECTED_TO(:,:)

!Timing variables
REAL*8, DIMENSION(2) :: t_LOOP 
REAL*8, DIMENSION(2) :: t_FORCECALC
REAL*8, DIMENSION(2) :: t_VIRTUAL_DEF, t_UPDATE_NEIGHBOURLIST
REAL*8, DIMENSION(2) :: t_MAPS_atom, t_MAPS_bead, t_LINKS_atom, t_LINKS_bead
REAL*8, DIMENSION(2) :: t_NEW_NEIGHBOUR_atom, t_NEW_NEIGHBOUR_bead
REAL*8, DIMENSION(2) :: t_NEW_FORCE, t_NONBONDED_atom, t_NONBONDED_bead, t_DISTRIBUTE_VSFORCE
REAL*8, DIMENSION(2) :: t_BONDED_FORCE, t_BONDS, t_ANGLES, t_TORSIONS, t_OUTOFPLANES
REAL*8, DIMENSION(2) :: t_SHIFT, t_MOVE, t_MOMENTUM, t_SCALEBP
REAL*8, DIMENSION(2) :: t_REPORTRESULTS, t_AVERAGE, t_WRITETRJ, t_OUTPUT
!End timing variables

INTEGER, POINTER :: LIST_ATOM(:,:)
INTEGER, POINTER :: LIST_BEAD(:,:)

INTEGER, POINTER :: CELL_ATOM(:), NCELL_ATOM(:), MAP_ATOM(:),LCLIST_ATOM(:),HEAD_ATOM(:),INDX_ATOM(:,:)
INTEGER, POINTER :: CELL_BEAD(:), NCELL_BEAD(:), MAP_BEAD(:),LCLIST_BEAD(:),HEAD_BEAD(:),INDX_BEAD(:,:)

INTEGER, POINTER :: VLCLIST(:),VHEAD(:), VCELL(:), INDEX_VSITE(:), VITYPE(:)

INTEGER, POINTER :: NATM(:), ITYPE(:), JBOND(:,:)
INTEGER :: NONBOND
INTEGER, POINTER :: NBONDS(:), NIJK(:), NIJKL(:), NOOPIJKL(:)
INTEGER, POINTER :: ATIANG(:)                                           !RECORD TYPE OF ATOMS WHICH HAS ANGLE INTERACTIONS
INTEGER, POINTER :: Z_POSITION(:)
INTEGER, POINTER :: NOANGLEIJK(:),FNIJKL(:) 
INTEGER, POINTER :: TYPE_LABEL(:), INDEX_BEAD(:,:),TYPE_BEAD(:)
INTEGER, POINTER :: COMVECT(:), COMPCOM(:,:),TYPECOM(:)
INTEGER, POINTER :: NDATB(:),NDATAN(:),NDATT(:),NDATNB(:), NDATO(:)

REAL(KIND=RKIND) :: RLIST_ATOM, RLISTSQ_ATOM, RCUT_ATOM, RCUTSQ_ATOM
REAL(KIND=RKIND) :: RLIST_BEAD, RLISTSQ_BEAD, RCUT_BEAD, RCUTSQ_BEAD

REAL(KIND=RKIND) :: KB, NA
PARAMETER ( NA = 6.0221367D+23 ,KB = 1.380658D-23)

REAL(KIND=RKIND) :: MMOLY, MASSSCALE, RSCALE, ESCALE,VISCOSITY,RVISCOSITY
REAL(KIND=RKIND) :: TEMP0, DT0, TAUT0, TAUP0, PRESSURE0, INITIME,RCUTDPD
REAL(KIND=RKIND) :: MKTEMP, VOLUME, INV_VOLUME
REAL(KIND=RKIND) :: TEMP, DT, TAUT, TAUP, PRESSURE, TIN, DT2, DTSQ2
REAL(KIND=RKIND) :: TEMPSCALE, PSCALE, TIMESCALE, FSCALE, DSCALE, VSCALE
REAL(KIND=RKIND) :: BOXX, BOXY, BOXZ, BOXXINV, BOXYINV, BOXZINV, TOTMASS
REAL(KIND=RKIND) :: R2D, D2R, FAC, CONV, BOXX2, BOXY2, BOXZ2
REAL(KIND=RKIND) :: VBOND, VANGLE
REAL(KIND=RKIND) :: VNBOND_ATOM, VBOND_ATOM, VANGLE_ATOM, VTOR, VNBOND_TOTAL
REAL(KIND=RKIND) :: VNBOND_BEAD, VBOND_BEAD, VANGLE_BEAD
REAL(KIND=RKIND) :: VNBOND_MIX, VNBOND_MIX2
REAL(KIND=RKIND) ::  TEK
REAL(KIND=RKIND) :: VOOP
REAL(KIND=RKIND) :: TVNBOND, TVBOND, TVANGLE, TVTOR
REAL(KIND=RKIND) :: BETA, BETA0, PFAC, CM
REAL(KIND=RKIND) :: PT23, PT11, PT22, PT33, PT13, PT12
REAL(KIND=RKIND) :: LX, LY, LZ
REAL(KIND=RKIND) :: RPT33, RPT12, RPT13, RVTOR, RVANGLE
REAL(KIND=RKIND) :: RVOOP
REAL(KIND=RKIND) :: RDENS, RVOL, RBOXZ, RBOXY, RBOXX, RPT11, RPT22
REAL(KIND=RKIND) :: RPT23, RP, RTEMP, RE, RV, REK, RVBOND, RVNBOND
REAL(KIND=RKIND) :: EXTER_FX,LAFREQ,DEN1,DEN2,RDEN1,RDEN2,RV_AVE1,RV_AVE2
REAL(KIND=RKIND) :: rfac, sigma,gamma,VVCONST,VVCONST0
REAL(KIND=RKIND), POINTER :: VIRTRX(:), VIRTRY(:),VIRTRZ(:)
REAL(KIND=RKIND), POINTER :: RX(:), RY(:), RZ(:), VX(:), VY(:), VZ(:)
REAL(KIND=RKIND), POINTER :: VTX(:),VTY(:),VTZ(:)
REAL(KIND=RKIND), allocatable :: FX(:), FY(:), FZ(:)
REAL(KIND=RKIND), allocatable :: FXNB(:), FYNB(:), FZNB(:)
REAL(KIND=RKIND), allocatable :: VFXNB(:), VFYNB(:), VFZNB(:)
REAL(KIND=RKIND), POINTER :: RBOND(:,:), BOND_FORCE(:,:), BOND_POT(:,:) 
REAL(KIND=RKIND), POINTER :: RNBOND(:,:), NBOND_FORCE(:,:), NBOND_POT(:,:) 
REAL(KIND=RKIND), POINTER :: ANGLE(:,:), BEND_FORCE(:,:), BEND_POT(:,:)
REAL(KIND=RKIND), POINTER :: ANGLE_TOR(:,:), TOR_FORCE(:,:), TOR_POT(:,:)
REAL(KIND=RKIND), POINTER :: ANGLE_OOP(:,:), OOP_FORCE(:,:), OOP_POT(:,:)
REAL(KIND=RKIND), POINTER :: MASS(:), INVMASS(:), MASS0(:), BINNB(:), BINB(:), BINA(:),BEADMASS(:)
REAL(KIND=RKIND), POINTER :: GB(:,:), GA(:,:), LB(:), LA(:), BINT(:)
REAL(KIND=RKIND), POINTER :: SX(:), SY(:), SZ(:), BINO(:)
REAL(KIND=RKIND), POINTER :: STEK(:), STVBOND(:), STVNBOND(:), STVTOR(:), STVOOP(:)
REAL(KIND=RKIND), POINTER :: STVANGLE(:), STV(:), STPT12(:)
REAL(KIND=RKIND), POINTER :: STE(:), STEMP(:), STPT11(:), STPT22(:), STPT33(:)
REAL(KIND=RKIND), POINTER :: STPT13(:), STPT23(:), STP(:), SP(:)
REAL(KIND=RKIND), POINTER :: SBOXX(:), SBOXY(:), SBOXZ(:), SVOL(:), SDENS(:)
REAL(KIND=RKIND), POINTER :: NUM(:),DENSITY(:),TEEMP(:),VXPRO(:),VPX(:)
REAL(KIND=RKIND), POINTER :: RVXPRO(:),RDENSITY(:),RTEEMP(:),PZX(:),RPZX(:)
REAL(KIND=RKIND), POINTER :: VVISCOSITY(:),RVVISCOSITY(:)
REAL(KIND=RKIND), POINTER ::  TOTBMASS(:),INVTOTBMASS(:) 
  REAL(KIND=RKIND),PARAMETER :: PI= 3.141592653589793238462643383279
       
    ! Variables for DPD 
REAL(KIND=RKIND) TFAC
INTEGER DPD_BONDED
INTEGER, POINTER :: DPDLIST(:),DPDPOINT(:)
REAL(KIND=RKIND), POINTER ::  VXO(:),  VYO(:), VZO(:)
!INTEGER, POINTER :: VDPDLIST(:),VDPDPOINT(:)
!       REAL(KIND=RKIND)  BETAT 

!     Variables for Hybrid Description
INTEGER :: NUM_BEAD = 0,timestepcheck,nonbondvirt, NUM_VS = 0, NUM_BA=0
INTEGER :: NB
integer :: contactB=0, contactA=0
INTEGER,POINTER :: INDEX_AB(:),virtNmol(:)
INTEGER, POINTER :: VIRT_NUMATOMS(:), VIRT_CENTER(:), VIRT_VS_IND(:), VIRT_ATM_IND(:,:)
REAL(KIND=RKIND), POINTER :: VIRT_MASS(:), VIRT_INVMASS(:), VIRT_MASSCOEFF(:,:)
real(kind=rkind) :: FCUTA,FCUTB
real(kind=rkind) :: VBOND_MIX, VANGLE_MIX, VTOR_MIX, VOOP_MIX
real(kind=rkind) :: VNBOND_CG, VBOND_CG, VANGLE_CG, VTOR_CG, VOOP_CG
real(kind=rkind) :: RVBOND_MIX, RVANGLE_MIX, RVTOR_MIX, RVOOP_MIX, RVNBOND_MIX
real(kind=rkind) :: RVNBOND_CG, RVBOND_CG, RVANGLE_CG, RVTOR_CG, RVOOP_CG
real(kind=rkind) :: RVBOND_At, RVANGLE_At, RVTOR_At, RVOOP_At, RVNBOND_At
REAL(kind=rkind), POINTER :: STVBOND_MIX(:), STVNBOND_MIX(:), STVTOR_MIX(:), STVOOP_MIX(:)
REAL(kind=rkind), POINTER :: STVANGLE_MIX(:), STV_MIX(:)
REAL(kind=rkind), POINTER :: STVBOND_CG(:), STVNBOND_CG(:), STVTOR_CG(:), STVOOP_CG(:)
REAL(kind=rkind), POINTER :: STVANGLE_CG(:), STV_CG(:)
REAL(kind=rkind), POINTER :: STVBOND_At(:), STVNBOND_At(:), STVTOR_At(:), STVOOP_At(:)
REAL(kind=rkind), POINTER :: STVANGLE_At(:), STV_At(:)
 character(len=18) :: name_file_virt
 character(len=7),pointer  :: name_mol(:) 
 character(len=2),dimension(18) :: name_label='NU'  
INTEGER :: NUMATOMS, NUMBEADS
INTEGER, POINTER :: ATOM(:), BEAD(:)

#ifdef DEBUG_OOP
!     Variables for Testing the OOP with the Atomistic PolyStyrene
REAL(KIND=RKIND) :: VOOP_ring,VOOP_LD,VOOP_L,VOOP_D
#endif



!     Variables for MTS
INTEGER :: MTS_CHECK,type_mts,I0,I1,I2,I3,I4,I5,MTSPARAM2,TSMTS,MTSPARAM,Kmts
reaL(KIND=RKIND) :: idt,idt2,idt3,idt4,idt5,mtsdt2,dt3,dt4,dt5
REAL(KIND=RKIND),POINTER :: FXi0(:),FYi0(:),FZi0(:) 
REAL(KIND=RKIND),POINTER :: FXi1(:),FYi1(:),FZi1(:) 
REAL(KIND=RKIND),POINTER :: FXii(:),FYii(:),FZii(:) 
REAL(KIND=RKIND),POINTER :: FXiii(:),FYiii(:),FZiii(:) 
REAL(KIND=RKIND),POINTER :: FXiiii(:),FYiiii(:),FZiiii(:) 
REAL(KIND=RKIND),POINTER :: FXv(:),FYv(:),FZv(:) 
REAL(KIND=RKIND),POINTER :: FXprova(:),FYprova(:),FZprova(:) 

!    Variables for SHAKE

integer,parameter :: maxit=200
real(kind=rkind),parameter :: tol=1.0E-10,rptol=1.0E-6
real(kind=rkind),pointer :: constr(:)
logical :: noBond,shakeOK
logical,pointer :: typeBond(:)


!***************************************

 CHARACTER(80), POINTER :: LABEL(:)
 CHARACTER(72) :: TITLE, NEIGHBORLIST
 CHARACTER(len=2):: TYn
 CHARACTER(1) day(9)
 INTEGER :: iseed       !for RANDOM NUMBER generator
END MODULE VAR
