!> @file
!> @brief Resets the net momentum
!> @details Called from NEW_LOOP.f90

SUBROUTINE MOMENTUM ()

  USE VAR
  IMPLICIT NONE

  INTEGER :: I, TI
  REAL*4 :: SUMX, SUMY, SUMZ, REG_MASS, INV_MASS

  SUMX = 0.0D0
  SUMY = 0.0D0
  SUMZ = 0.0D0

  DO I = 1, NATOMS
     TI = ITYPE(I)
     REG_MASS = MASS(TI)
     SUMX = SUMX + VX(I) * REG_MASS
     SUMY = SUMY + VY(I) * REG_MASS
     SUMZ = SUMZ + VZ(I) * REG_MASS
  END DO

  SUMX = SUMX/REAL (NATOMS)
  SUMY = SUMY/REAL (NATOMS)
  SUMZ = SUMZ/REAL (NATOMS)

  !	CHANGE THE VELOCITES SUCH THAT TOTAL MOMENTUM IN EACH DIRECTION IS SETED TO ZERO
  DO I = 1, NATOMS
     TI = ITYPE(I)
     INV_MASS = INVMASS(TI)
     VX(I) = VX(I) - SUMX*INV_MASS
     VY(I) = VY(I) - SUMY*INV_MASS
     VZ(I) = VZ(I) - SUMZ*INV_MASS
  END DO

  RETURN
END SUBROUTINE MOMENTUM
