SUBROUTINE NEW_FORCE()

  USE VAR

  IMPLICIT NONE

  INTEGER :: I, A, J
  REAL(KIND=RKIND) :: RXIJ, RYIJ, RZIJ, RIJSQ

  !Reset all forces
  FX = 0.0D0
  FY = 0.0D0
  FZ = 0.0D0
  VFXNB      = 0.0D0
  VFYNB      = 0.0D0
  VFZNB      = 0.0D0

  PT11 = 0.0D0
  PT22 = 0.0D0
  PT33 = 0.0D0
  PT12 = 0.0D0
  PT13 = 0.0D0
  PT23 = 0.0D0

  VNBOND_ATOM     = 0.0D0
  VNBOND_BEAD = 0.0D0
  VBOND = 0.0D0
  VANGLE = 0.0D0
  VTOR       = 0.0D0
  VOOP       = 0.0D0

DO A=POINT_BEAD(1),POINT_BEAD(2)-1
   J = LIST_BEAD(A)
   RXIJ = RX(1) - RX(J)
   RYIJ = RY(1) - RY(J)
   RZIJ = RZ(1) - RZ(J)
   RXIJ = RXIJ - ANINT ( RXIJ * BOXXINV ) * BOXX
   RYIJ = RYIJ - ANINT ( RYIJ * BOXYINV ) * BOXY
   RZIJ = RZIJ - ANINT ( RZIJ * BOXZINV ) * BOXZ
   RIJSQ = RXIJ ** 2.0D0 + RYIJ ** 2.0D0 + RZIJ ** 2.0D0
      WRITE(9999,*) LIST_BEAD(A), sqrt(rijsq)
END DO

E_ATOM = 0.0D0
E_MIX = 0.0D0
E_CG = 0.0D0



  !Nonbonded forces
  CALL NONBONDED_FORCE(NUMATOMS,ATOM,POINT_ATOM,MAXNAB_ATOM,LIST_ATOM,VNBOND_ATOM,RCUT_ATOM,RCUTSQ_ATOM)

  IF(IBRDESCR .eq. 0) THEN
     CALL NONBONDED_FORCE(NCOARSE,BEAD,POINT_BEAD,MAXNAB_BEAD,LIST_BEAD,VNBOND_BEAD,RCUT_BEAD,RCUTSQ_BEAD)
     CALL DISTRIBUTE_VSFORCE() !Distributes forces from VS onto the atoms underneath
  END IF

  WRITE(*,*) 'ATOM', E_ATOM*conv
  WRITE(*,*) 'MIX', E_MIX*conv
  WRITE(*,*) 'CG', E_CG*conv

  !Bonded forces
  CALL BONDED_FORCE()

  RETURN
END SUBROUTINE NEW_FORCE
