SUBROUTINE RDVIRTUAL()

USE VAR

IMPLICIT NONE

INTEGER :: iost, I, J, K
INTEGER, PARAMETER :: NBEAD = 15 !Max number of atoms within a VS
REAL(KIND=RKIND) :: SUMTOTX, SUMTOTY, SUMTOTZ
REAL(KIND=RKIND) :: RPX, RPY, RPZ, SPX, SPY, SPZ


OPEN(UNIT=10,FILE='virtual',status='old',IOSTAT=iost)

IF(iost .ne. 0) THEN
   WRITE(*,*) '*** FATAL ERROR! File virtual site does not exist ****'
   WRITE(1,*) '*** FATAL ERROR! File virtual site does not exist ****'
   ISTOP=1
   RETURN
END IF

READ(10,*)
READ(10,*)
READ(10,*) NVIRTA
READ(10,*)
READ(10,*)

NB = 2 !FIX THIS 

ALLOCATE(VIRTRX(NVIRTA))
ALLOCATE(VIRTRY(NVIRTA))
ALLOCATE(VIRTRZ(NVIRTA))
ALLOCATE(INDEX_VSITE(NVIRTA))
ALLOCATE(TYPE_BEAD(NB))
ALLOCATE(NUMATOM(NB))
numatom = 8 !FIX THIS
ALLOCATE(TOTBMASS(NVIRTA))
ALLOCATE(INVTOTBMASS(NVIRTA))
ALLOCATE(VITYPE(NVIRTA))
allocate(init_numbcomp(nvirta))
ALLOCATE(masscoeff(NVIRTA,NBEAD))
ALLOCATE(VIRT_POINT_SEC(NVIRTA+1))
ALLOCATE(VCELL(NVIRTA))
ALLOCATE(VLCLIST(NVIRTA))
ALLOCATE(INDX_ATM(NVIRTA,NBEAD))
ALLOCATE(virtual_center(NATOMS))

ALLOCATE(COMPCOM(NVIRTA,NBEAD))
compcom = 0

indx_atm = 0
virtual_center = 0

TOTBMASS = 0
INVTOTBMASS = 0
masscoeff=0

!Read virtual site information

DO I=1,NVIRTA
   read(10,*) K, VITYPE(I), INIT_NUMBCOMP(I), INDEX_VSITE(I)
   read(10,*,IOSTAT=iost) (INDX_ATM(I,J), J=1,INIT_NUMBCOMP(I))

   DO J=1,INIT_NUMBCOMP(I)
      COMPCOM(I,J) = INDX_ATM(I,J)
   END DO
   
   !If INDEX_VSITE = 0 then COM else update the virtual_center
   if(INDEX_VSITE(I) .ne. 0) then
      virtual_center(INDEX_VSITE(I)) = I
   end if

   IF(iost .ne. 0) THEN
      WRITE(*,*) 'ERROR READING VIRTUAL, TOO SHORT'
      WRITE(1,*) 'ERROR READING VIRTUAL, TOO SHORT'
      ISTOP = 1
      RETURN
   END IF
END DO

RETURN
END SUBROUTINE RDVIRTUAL
