#include "ibi-preprocess.h"

SUBROUTINE UPDATE_NEIGHBOURLIST()

  USE VAR
  USE OMP_LIB

  IMPLICIT NONE

  INTEGER :: A, I

  IF (ENSEMBLE == 2) THEN !If NPT
#ifdef TIMING_ON
     t_MAPS_atom(1) = OMP_GET_WTIME()
#endif
     !Update the size of cells and corresponding map of cells.
     NCELLX_ATOM = BOXX / RLIST_ATOM
     NCELLY_ATOM = BOXY / RLIST_ATOM
     NCELLZ_ATOM = BOXZ / RLIST_ATOM

     NUMCELL_ATOM = NCELLX_ATOM * NCELLY_ATOM * NCELLZ_ATOM 

     CALL MAPS (MAP_ATOM,MAPSIZE_ATOM &
          , NCELLX_ATOM, NCELLY_ATOM, NCELLZ_ATOM) 

#ifdef TIMING_ON
     t_MAPS_atom(2) = OMP_GET_WTIME()
#endif

     IF(IBRDESCR .eq. 0) THEN
#ifdef TIMING_ON
        t_MAPS_bead(1) = OMP_GET_WTIME()
#endif
        NCELLX_BEAD = BOXX / RLIST_BEAD
        NCELLY_BEAD = BOXY / RLIST_BEAD
        NCELLZ_BEAD = BOXZ / RLIST_BEAD

        NUMCELL_BEAD = NCELLX_BEAD * NCELLY_BEAD * NCELLZ_BEAD 

        CALL MAPS (MAP_BEAD,MAPSIZE_BEAD &
             , NCELLX_BEAD, NCELLY_BEAD, NCELLZ_BEAD) 
#ifdef TIMING_ON
        t_MAPS_bead(2) = OMP_GET_WTIME()
#endif
     END IF
  END IF !If NPT

#ifdef TIMING_ON
  t_LINKS_atom(1) = OMP_GET_WTIME()
#endif
  CALL LINKS (HEAD_ATOM,MAXNUMCELL_ATOM,ATOM,NUMATOMS,CELL_ATOM &
       , NCELLX_ATOM, NCELLY_ATOM, NCELLZ_ATOM, LCLIST_ATOM)

#ifdef TIMING_ON
  t_LINKS_atom(2) = OMP_GET_WTIME()
  t_NEW_NEIGHBOUR_atom(1) = OMP_GET_WTIME()
#endif

  CALL NEW_NEIGHBOUR_WITHLIST(ATOM,CELL_ATOM,LCLIST_ATOM,NUMATOMS,RLIST_ATOM &
       , LIST_ATOM, MAXNAB_ATOM, MAP_ATOM, MAXMAPSIZE_ATOM, HEAD_ATOM, MAXNUMCELL_ATOM)

#ifdef TIMING_ON
  t_NEW_NEIGHBOUR_atom(2) = OMP_GET_WTIME()
#endif

  IF(IBRDESCR .eq. 0) THEN
#ifdef TIMING_ON
     t_LINKS_bead(1) = OMP_GET_WTIME()
#endif
     CALL LINKS (HEAD_BEAD,MAXNUMCELL_BEAD,BEAD,NCOARSE,CELL_BEAD &
          , NCELLX_BEAD, NCELLY_BEAD, NCELLZ_BEAD, LCLIST_BEAD)

#ifdef TIMING_ON
     t_LINKS_bead(2) = OMP_GET_WTIME()
     t_NEW_NEIGHBOUR_bead(1) = OMP_GET_WTIME()
#endif

     CALL NEW_NEIGHBOUR_WITHLIST(BEAD,CELL_BEAD,LCLIST_BEAD,NCOARSE,RLIST_BEAD &
          , LIST_BEAD, MAXNAB_BEAD, MAP_BEAD, MAXMAPSIZE_BEAD, HEAD_BEAD, MAXNUMCELL_BEAD)
#ifdef TIMING_ON
     t_NEW_NEIGHBOUR_bead(2) = OMP_GET_WTIME()
#endif
  END IF

  RETURN
END SUBROUTINE UPDATE_NEIGHBOURLIST
