!> @file
!> @brief Writes s-md.psf, used for later analysis

SUBROUTINE WRITEPSF()

  USE VAR

  IMPLICIT NONE

  INTEGER :: I, J, A
  INTEGER :: NBONDS_PSF, NTHETA, NPHI, NOOP !Number of each topology type
  INTEGER :: TOP_LIMIT, NOTOPOLOGY
  INTEGER :: NLINES, P
  INTEGER, ALLOCATABLE :: BONDLIST(:,:), ANGLELIST(:,:), TORSIONLIST(:,:), OOPLIST(:,:)

  TOP_LIMIT = 2 * NATOMS !Maximum number of expected bonds
  ALLOCATE(BONDLIST(TOP_LIMIT,2), ANGLELIST(TOP_LIMIT,3), TORSIONLIST(TOP_LIMIT,4), OOPLIST(TOP_LIMIT,4))

  !Count bonds and build lists
  NBONDS_PSF = 0
  NTHETA = 0
  NPHI  = 0
  NOOP = 0
  NOTOPOLOGY = 0
  DO I=1,NATOMS
     DO J=1,NBONDS(I)
        IF (JBOND(I,J) > I) THEN
           NBONDS_PSF = NBONDS_PSF + 1
           IF(NBONDS_PSF > TOP_LIMIT) THEN
              NOTOPOLOGY = 1
           ELSE
              BONDLIST(NBONDS_PSF, 1) = I
              BONDLIST(NBONDS_PSF, 2) = JBOND(I,J)                                                                     
           END IF
        END IF
     END DO

     DO J=1,NIJK(I)
        NTHETA = NTHETA + 1
        IF(I .LE. NATOMS .AND. JANGLEIJK(I,J) .LE. NATOMS .AND. &
             KANGLEIJK(I,J) .LE. NATOMS) THEN !Check the angle isn't a virtual site angle
           IF(NTHETA > TOP_LIMIT) THEN
              NOTOPOLOGY = 1
           ELSE
              ANGLELIST(NTHETA,1) = I
              ANGLELIST(NTHETA,2) = JANGLEIJK(I,J)
              ANGLELIST(NTHETA,3) = KANGLEIJK(I,J)
           END IF
        END IF
     END DO

     DO J=1,NIJKL(I)
        NPHI = NPHI + 1
        IF(NPHI > TOP_LIMIT) THEN
           NOTOPOLOGY = 1
        ELSE
           TORSIONLIST(NPHI,1) = I
           TORSIONLIST(NPHI,2) = JTORIJKL(I,J)
           TORSIONLIST(NPHI,3) = KTORIJKL(I,J)
           TORSIONLIST(NPHI,4) = LTORIJKL(I,J)
        END IF
     END DO

     DO J=1,NOOPIJKL(I)
        NOOP = NOOP + 1
        IF(NOOP > TOP_LIMIT) THEN
           NOTOPOLOGY = 1
        ELSE
           OOPLIST(NOOP,1) = I
           OOPLIST(NOOP,2) = JOOPIJKL(I,J)
           OOPLIST(NOOP,3) = KOOPIJKL(I,J)
           OOPLIST(NOOP,4) = LOOPIJKL(I,J)
        END IF
     END DO
  END DO

  OPEN(UNIT=117, FILE='s-md.psf')
  WRITE(117,"(A3)") 'PSF'
  WRITE(117,*) ''
  WRITE(117,*) '2 !NTITLE'
  WRITE(117,*) '  REMARKS: PSF file for system :', TITLE
  WRITE(117,*) '  REMARKS: Automatically generated by IBIsCO'
  WRITE(117,*) ''
  WRITE(117,*) ' ',NATOMS,' !NATOM'
  DO I=1,NATOMS
     WRITE(117,1001) I, NAME_MOL(MOL(I)), MOL(I), NAME_MOL(MOL(I)), LABEL(ITYPE(I)), ITYPE(I), 0.00, MASS0(ITYPE(I)), 0
  END DO
1001 FORMAT (I6, 1X, A7, 1X, I6, 1X, A7, 1X, A7, 1X, I6, 1X, F5.2, 1X, E12.5, 1X, I1)
  WRITE(117,*) ''

  IF( NOTOPOLOGY .EQ. 0) THEN
     !Bonds
     IF( NBONDS_PSF > 0) THEN
        WRITE(117,*) '  ',NBONDS_PSF,' !NBOND'
        NLINES = NBONDS_PSF / 4
        P = 1 !Position within the bond array
        DO I=1,NLINES
           WRITE(117,*) BONDLIST(P,1), BONDLIST(P,2), BONDLIST(P+1,1), BONDLIST(P+1,2), &
                BONDLIST(P+2,1), BONDLIST(P+2,2), BONDLIST(P+3,1), BONDLIST(P+3,2)
           P = P + 4
        END DO

        SELECT CASE(MOD(NBONDS_PSF,4))
        CASE(1)
           P = NBONDS_PSF
           WRITE(117,*) BONDLIST(P,1), BONDLIST(P,2)
        CASE(2)
           P = NBONDS_PSF - 1
           WRITE(117,*) BONDLIST(P,1), BONDLIST(P,2), BONDLIST(P+1,1), BONDLIST(P+1,2)
        CASE(3)
           P = NBONDS_PSF - 2
           WRITE(117,*) BONDLIST(P,1), BONDLIST(P,2), BONDLIST(P+1,2), BONDLIST(P+1,2), &
                BONDLIST(P+2,1), BONDLIST(P+2,2)
        END SELECT
        WRITE(117,*) ''
     END IF
     !Angles
     IF( NTHETA > 0) THEN
        WRITE(117,*) '  ',NTHETA,' !NTHETA'
        NLINES = NTHETA / 3
        P = 1
        DO I=1,NLINES
           WRITE(117,*) ANGLELIST(P,1), ANGLELIST(P,2), ANGLELIST(P,3), &
                ANGLELIST(P+1,1), ANGLELIST(P+1,2), ANGLELIST(P+1,3), &
                ANGLELIST(P+2,1), ANGLELIST(P+2,2), ANGLELIST(P+2,3)
           P = P + 3
        END DO

        SELECT CASE(MOD(NTHETA,4))
        CASE(1)
           P = NTHETA
           WRITE(117,*) ANGLELIST(P,1), ANGLELIST(P,2), ANGLELIST(P,3)
        CASE(2)
           P = NTHETA - 1
           WRITE(117,*) ANGLELIST(P,1), ANGLELIST(P,2), ANGLELIST(P,3), &
                ANGLELIST(P+1,1), ANGLELIST(P+1,2), ANGLELIST(P+1,3)
        END SELECT
        WRITE(117,*) ''
     END IF
     !Torsions
     IF( NPHI > 0) THEN
        WRITE(117,*) '  ',NPHI,' !NPHI'
        NLINES = NPHI / 2
        P = 1
        DO I=1,NLINES
           WRITE(117,*) TORSIONLIST(P,1), TORSIONLIST(P,2), TORSIONLIST(P,3), TORSIONLIST(P,4), &
                TORSIONLIST(P+1,1), TORSIONLIST(P+1,2), TORSIONLIST(P+1,3), TORSIONLIST(P+1,4)
           P = P + 2
        END DO

        IF(MOD(NPHI,2) .EQ. 1) THEN
           WRITE(117,*) TORSIONLIST(NPHI,1), TORSIONLIST(NPHI,2), TORSIONLIST(NPHI,3), TORSIONLIST(NPHI,4)
        END IF
        WRITE(117,*) ''
     END IF
     !OOPs
     IF( NOOP > 0) THEN
        WRITE(117,*) '  ',NOOP,' !NIMPHI'
        NLINES = NOOP / 2
        P = 1
        DO I=1,NLINES
           WRITE(117,*) OOPLIST(P,1), OOPLIST(P,2), OOPLIST(P,3), OOPLIST(P,4), &
                OOPLIST(P+1,1), OOPLIST(P+1,2), OOPLIST(P+1,3), OOPLIST(P+1,4)
           P = P + 2
        END DO

        IF(MOD(NOOP,2) .EQ. 1) THEN
           WRITE(117,*) OOPLIST(NOOP,1), OOPLIST(NOOP,2), OOPLIST(NOOP,3), OOPLIST(NOOP,4)
        END IF
        WRITE(117,*) ''
     END IF
  ELSE
     WRITE(*,*) 'Writing topology section of PSF failed'
     WRITE(1,*) 'Writing topology section of PSF failed'
  END IF

  CLOSE(117)

  DEALLOCATE(BONDLIST, ANGLELIST, TORSIONLIST, OOPLIST)

  RETURN
END SUBROUTINE WRITEPSF
